# Generated by Django 3.1.3 on 2020-11-05 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_auto_20201105_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gamer_id',
            new_name='gamer',
        ),
    ]
