# Generated by Django 3.1.3 on 2020-11-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0003_auto_20201105_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='gamecategory',
            old_name='game_id',
            new_name='game',
        ),
    ]
